global:
  scrape_interval: 15s
  scrape_timeout: 10s
scrape_configs:
  - job_name: "auth-service"
    static_configs:
      - targets:
        - auth-service:3000
  - job_name: "prometheus"
    static_configs:
      - targets:
        - localhost:9090
  - job_name: docker
    static_configs:
      - targets:
        - host.docker.internal:9323